"use strict";

const CURRENCY = {
    BTC_USD: "btcusd",
    BTC_EUR: "btceur",
    BTC_GBP: "btcgbp",
    BTC_PAX: "btcpax",
    GBP_USD: "gbpusd",
    GBP_EUR: "gbpeur",
    EUR_USD: "eurusd",
    XRP_USD: "xrpusd",
    XRP_EUR: "xrpeur",
    XRP_BTC: "xrpbtc",
    XRP_GBP: "xrpgbp",
    XRP_PAX: "xrppax",
    LTC_USD: "ltcusd",
    LTC_EUR: "ltceur",
    LTC_BTC: "ltcbtc",
    LTC_GBP: "ltcgbp",
    ETH_USD: "ethusd",
    ETH_EUR: "etheur",
    ETH_BTC: "ethbtc",
    ETH_GBP: "ethgbp",
    ETH_PAX: "ethpax",
    BCH_USD: "bchusd",
    BCH_EUR: "bcheur",
    BCH_BTC: "bchbtc",
    BCH_GBP: "bchgbp",
    PAX_USD: "paxusd",
    PAX_EUR: "paxeur",
    PAX_GBP: "paxgbp",
    XLM_BTC: "xlmbtc",
    XLM_USD: "xlmusd",
    XLM_EUR: "xlmeur",
    XLM_GBP: "xlmgbp",
};

module.exports = CURRENCY;
